backend:
  name: github
  repo: dirtyredz/rusty-universe.com

media_folder: static/assets

collections:
  - name: servers
    label: Servers
    folder: servers
    create: true
    fields:
      - { name: title, label: Title, widget: "string"}
      - { name: country, label: Country, widget: "select", options: ["EU", "US"]}
      - { name: pvp, label: PvP, widget: "string"}
      - { name: description, label: Description, widget: "string"}
      - { name: ip, label: IP, widget: "string"}
      - { name: interface, label: Interface, widget: "string"}
  - name: rewards
    label: Rewards
    folder: rewards
    create: true
    fields:
      - { name: title, label: Title, widget: "string"}
      - { name: description, label: Description, widget: "string"}
      - { name: icon, label: Icon, widget: "select", options: ["Radar", "Mining", "BackForth", "Aerosol", "Discord", "Computer", "Coins"] }
  - name: ranks
    label: Ranks
    folder: ranks
    create: true
    fields:
      - { name: title, label: Title, widget: "string"}
      - { name: description, label: Description, widget: "string"}
      - { name: amount, label: "Currency Amount", widget: "number"}
      - name: rankRewards
        label: Rank Rewards
        widget: list
        fields:
            - { name: amount, label: Amount, widget: "number"}
            - label: "Reward"
              name: "reward"
              widget: "relation"
              collection: "rewards"
              searchFields: ["description", "title"]
              valueField: "title"